import java.net.http.HttpRequest;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Paths;

public class Main {

    //lista dos filmes (o site do omdb não tem e o do imdb precisa da aws)
    static String[] filmes = {
        "The+Shawshank+Redemption",
        "The+Godfather",
        "The+Dark+Knight",
        "The+Godfather+Part+II",
        "12+Angry+Men",
        "The+Lord+of+the+Rings:+The+Return+of+the+King",
        "Schindler's+List",
        "Pulp+Fiction",
        "The+Lord+of+the+Rings:+The+Fellowship+of+the+Ring",
        "The+Good,+the+Bad+and+the+Ugly",
        "Forrest+Gump",
        "The+Lord+of+the+Rings:+The+Two+Towers",
        "Fight+Club",
        "Inception",
        "Star+Wars:+Episode+V+-+The+Empire+Strikes+Back",
        "The+Matrix",
        "Goodfellas",
        "Interstellar",
        "One+Flew+Over+the+Cuckoo's+Nest",
        "Se7en",
        "It's+a+Wonderful+Life",
        "The+Silence+of+the+Lambs",
        "Seven+Samurai",
        "Saving+Private+Ryan",
        "The+Green+Mile",
        "City+of+God",
        "Life+Is+Beautiful",
        "Terminator+2:+Judgment+Day",
        "Star+Wars:+Episode+IV+-+A+New+Hope",
        "Back+to+the+Future",
        "Spirited+Away",
        "The+Pianist",
        "Gladiator",
        "Parasite",
        "Psycho",
        "The+Lion+King",
        "Grave+of+the+Fireflies",
        "The+Departed",
        "Whiplash",
        "Harakiri",
        "The+Prestige",
        "American+History+X",
        "Léon:+The+Professional",
        "Spider-Man:+Across+the+Spider-Verse",
        "Casablanca",
        "The+Usual+Suspects",
        "Cinema+Paradiso",
        "The+Intouchables",
        "Alien",
        "Modern+Times",
        "Rear+Window",
        "Once+Upon+a+Time+in+the+West",
        "Django+Unchained",
        "City+Lights",
        "Apocalypse+Now",
        "WALL·E",
        "Memento",
        "Dune:+Part+Two",
        "Raiders+of+the+Lost+Ark",
        "Avengers:+Infinity+War",
        "The+Lives+of+Others",
        "Sunset+Blvd.",
        "Spider-Man:+Into+the+Spider-Verse",
        "Witness+for+the+Prosecution",
        "Paths+of+Glory",
        "The+Shining",
        "The+Great+Dictator",
        "12th+Fail",
        "Inglourious+Basterds",
        "Aliens",
        "The+Dark+Knight+Rises",
        "Coco",
        "Amadeus",
        "Avengers:+Endgame",
        "Toy+Story",
        "Good+Will+Hunting",
        "Dr.+Strangelove+or:+How+I+Learned+to+Stop+Worrying+and+Love+the+Bomb",
        "Oldboy",
        "Das+Boot",
        "Braveheart",
        "High+and+Low",
        "American+Beauty",
        "Princess+Mononoke",
        "Your+Name",
        "3+Idiots",
        "Joker",
        "Capernaum",
        "Once+Upon+a+Time+in+America",
        "Singin'+in+the+Rain",
        "Come+and+See",
        "Requiem+for+a+Dream",
        "Star+Wars:+Episode+VI+-+Return+of+the+Jedi",
        "Toy+Story+3",
        "The+Hunt",
        "Ikiru",
        "Eternal+Sunshine+of+the+Spotless+Mind",
        "Incendies",
        "2001:+A+Space+Odyssey",
        "The+Apartment",
        "Reservoir+Dogs",
        "Lawrence+of+Arabia",
        "Scarface",
        "Double+Indemnity",
        "Heat",
        "North+by+Northwest",
        "Up",
        "Citizen+Kane",
        "M",
        "Full+Metal+Jacket",
        "Vertigo",
        "Amelie",
        "Hababam+Sinifi+Sinifta+Kaldi",
        "Like+Stars+on+Earth",
        "A+Separation",
        "To+Kill+a+Mockingbird",
        "Die+Hard",
        "Indiana+Jones+and+the+Last+Crusade",
        "A+Clockwork+Orange",
        "The+Sting",
        "Metropolis",
        "Oppenheimer",
        "Snatch",
        "1917",
        "L.A.+Confidential",
        "Bicycle+Thieves",
        "Downfall",
        "Dangal",
        "The+Wolf+of+Wall+Street",
        "Hamilton",
        "Taxi+Driver",
        "Green+Book",
        "Batman+Begins",
        "The+Truman+Show",
        "For+a+Few+Dollars+More",
        "Judgment+at+Nuremberg",
        "Some+Like+It+Hot",
        "Shutter+Island",
        "The+Kid",
        "The+Father",
        "Jurassic+Park",
        "All+About+Eve",
        "There+Will+Be+Blood",
        "The+Sixth+Sense",
        "Ran",
        "Casino",
        "Top+Gun:+Maverick",
        "No+Country+for+Old+Men",
        "The+Thing",
        "Unforgiven",
        "Pan's+Labyrinth",
        "Kill+Bill:+Vol.+1",
        "A+Beautiful+Mind",
        "Prisoners",
        "The+Treasure+of+the+Sierra+Madre",
        "Yojimbo",
        "Finding+Nemo",
        "Howl's+Moving+Castle",
        "The+Great+Escape",
        "Monty+Python+and+the+Holy+Grail",
        "The+Elephant+Man",
        "Dial+M+for+Murder",
        "Klaus",
        "Gone+with+the+Wind",
        "Chinatown",
        "The+Secret+in+Their+Eyes",
        "Lock,+Stock+and+Two+Smoking+Barrels",
        "Rashomon",
        "V+for+Vendetta",
        "Inside+Out",
        "Three+Billboards+Outside+Ebbing,+Missouri",
        "Catch+Me+If+You+Can",
        "Trainspotting",
        "The+Bridge+on+the+River+Kwai",
        "Raging+Bull",
        "The+Wild+Robot",
        "Fargo",
        "Harry+Potter+and+the+Deathly+Hallows:+Part+2",
        "Warrior",
        "Gran+Torino",
        "Million+Dollar+Baby",
        "Ben-Hur",
        "Mad+Max:+Fury+Road",
        "My+Neighbor+Totoro",
        "Barry+Lyndon",
        "Dead+Poets+Society",
        "Children+of+Heaven",
        "Hacksaw+Ridge",
        "Spider-Man:+No+Way+Home",
        "The+Grand+Budapest+Hotel",
        "12+Years+a+Slave",
        "Before+Sunrise",
        "Blade+Runner",
        "Memories+of+Murder",
        "Gone+Girl",
        "Ratatouille",
        "How+to+Train+Your+Dragon",
        "Monsters,+Inc.",
        "In+the+Name+of+the+Father",
        "Jaws",
        "Wild+Tales",
        "The+Gold+Rush",
        "Sherlock+Jr.",
        "Ford+v+Ferrari",
        "Mary+and+Max",
        "The+Deer+Hunter",
        "The+Wages+of+Fear",
        "The+General",
        "Mr.+Smith+Goes+to+Washington",
        "On+the+Waterfront",
        "Logan",
        "Wild+Strawberries",
        "Rocky",
        "The+Third+Man",
        "Tokyo+Story",
        "Spotlight",
        "The+Terminator",
        "The+Big+Lebowski",
        "Pirates+of+the+Caribbean:+The+Curse+of+the+Black+Pearl",
        "The+Trash+Mystery",
        "The+Seventh+Seal",
        "La+Haine",
        "Room",
        "Jai+Bhim",
        "Hotel+Rwanda",
        "Platoon",
        "The+Best+Years+of+Our+Lives",
        "Before+Sunset",
        "The+Sound+of+Music",
        "The+Exorcist",
        "The+Incredibles",
        "The+Wizard+of+Oz",
        "Hachi:+A+Dog's+Tale",
        "Rush",
        "The+Passion+of+Joan+of+Arc",
        "Stand+by+Me",
        "My+Father+and+My+Son",
        "A+Silent+Voice",
        "The+Iron+Giant",
        "Network",
        "The+Handmaiden",
        "The+Battle+of+Algiers",
        "The+Grapes+of+Wrath",
        "To+Be+or+Not+to+Be",
        "Into+the+Wild",
        "Groundhog+Day",
        "The+Help",
        "Gangs+of+Wasseypur",
        "Drishyam",
        "Andhadhun",
        "Amores+Perros"
    };


    public static void main(String[] args) throws Exception{
        //chave do OMDb
        String apiKey = Files.readString(Paths.get("apikey.txt")).trim();

        //cliente HTTP
        HttpClient client = HttpClient.newHttpClient();

        System.out.println("250 Filmes mais bem avaliados segundo o IMDb");

        for(int i = 0; i < filmes.length; i++) {
            //URL de busca
            String url = "http://www.omdbapi.com/?t="+filmes[i]+"&apikey=" + apiKey;
            
            //requisição GET
            HttpRequest request = HttpRequest
                .newBuilder()
                .uri(URI.create(url))
                .GET()
                .build();
            
            //envio da requisição e resposta
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
        
            //impressão na tela
            System.out.println(response.body());
        }

        System.out.println("Fim da lista!");

    }
}
